
import { ReportOptions } from './types';

export const defaultReportOptions: ReportOptions = {
  watermarkText: 'Car Detective Report',
  logoUrl: '',
  showPremiumWatermark: false,
  includeExplanation: false,
  includeComparables: false,
  includeFooter: true,
  footerText: 'Generated by Car Detective © ' + new Date().getFullYear(),
  primaryColor: '#3B82F6',
  secondaryColor: '#0F172A',
  fonts: {
    titleFont: 'Helvetica-Bold',
    bodyFont: 'Helvetica',
  },
  isPremium: false,
  includeBranding: true,
  includePhotoAssessment: false,
  watermark: 'Car Detective Report'
};
